import { useEffect, useState } from 'react';
import { apiRequest } from './api/openapiClient';

/**
 * Deterministic UUID v5 for Turkey provinces (generated by BE StableProvinceID).
 * Mirrors Turkey official 81 provinces.
 */
export const PROVINCES_BY_UUID: Record<string, string> = {
  '802aa4c5-68d5-56e3-b5d8-c98b5d7f7874': 'Adana',
  'fa368f15-052c-58bd-8c22-af7643521553': 'Adıyaman',
  'c6cb4581-16fa-5faf-a4be-4c903baea061': 'Afyonkarahisar',
  '37e6351b-f88f-5b1e-8e6c-ba9c16c079d9': 'Ağrı',
  '104e21e3-a95a-5059-a63e-4058e5682dd0': 'Amasya',
  '2436cf3e-a250-511c-aa39-c5cd1c8a3f71': 'Ankara',
  '14585377-9641-5080-8462-ce6478d58998': 'Antalya',
  'd354d0ab-81ea-560c-ab4d-78ae1be3728a': 'Artvin',
  '4dfde5a5-7180-5cca-929a-96ee235d64f6': 'Aydın',
  'd4a872c2-5cf4-5342-9922-13dc022b290c': 'Balıkesir',
  '7c13f530-e799-51fe-ac09-a231cea4c1e7': 'Bilecik',
  'c6140cb5-5223-57f1-8863-bc925ba91e40': 'Bingöl',
  '85c5a693-64df-5bd9-a36e-977d5009cc9d': 'Bitlis',
  '16ec38a8-998d-5434-b2c7-c03e37ce0f82': 'Bolu',
  '4dfb23b5-1a55-595e-bdb7-9e863c122a10': 'Burdur',
  '47ff002c-f6f2-5c01-81a9-460b23ba9712': 'Bursa',
  'c46e86e7-5849-57bd-b16a-f4ac20d45c0e': 'Çanakkale',
  '64891a60-9e8b-5816-a5cc-cd79d8020a8f': 'Çankırı',
  '1f3d27ad-19e5-5ed5-8b11-09a431437376': 'Çorum',
  'c4f64530-3327-5c22-ba69-2dddca1d6e2e': 'Denizli',
  'b564f517-782a-51c4-9abf-a59ecfa62cc4': 'Diyarbakır',
  '3e06f957-1c15-503a-8bbc-01fbdad0107d': 'Edirne',
  'b9411ebc-c3d7-5ec7-a018-ff029831c002': 'Elazığ',
  '171805e7-c069-5516-947f-5a916285731f': 'Erzincan',
  '3bd7ddd4-06a9-5ce3-843c-b70db66391cc': 'Erzurum',
  'f99e4649-2d13-539a-92e1-12b7c6d03b12': 'Eskişehir',
  '19c22d95-f1f1-527f-b285-73156ced680e': 'Gaziantep',
  'ae7689a4-144a-5d86-86f8-afa06852692d': 'Giresun',
  '4d2aac2d-83bc-5c95-a213-7d7f26474cf2': 'Gümüşhane',
  'a4c5772b-0229-5fdc-abd1-a6ef99070af6': 'Hakkari',
  'b23f1024-95ad-509e-baa6-50a49b6818aa': 'Hatay',
  'd725a9a0-7a80-5015-9e87-afee888225d2': 'Isparta',
  '01d832aa-97c8-5eba-ae42-200bb7047edb': 'Mersin',
  'c029c5bf-570e-5eb2-9d0f-0437fa131ff1': 'İstanbul',
  '64f1681f-bd67-5b6d-a0fb-cb67e70dda74': 'İzmir',
  '46d0860f-e6f8-5324-ad1d-b493da199075': 'Kars',
  '59e3a858-d837-5f8a-bd15-dad0cb80848d': 'Kastamonu',
  'f7d1fef1-1ccd-5b23-bb91-d8242060ae31': 'Kayseri',
  '1b888d4e-2537-5b9b-b346-921d649e9ab2': 'Kırklareli',
  'a52e9c66-083d-51ae-b906-5fb3589e9a2f': 'Kırşehir',
  '99307140-598f-59c3-b219-892878bd5e7d': 'Kocaeli',
  '43d77888-0432-576d-93ef-24f834c8ebac': 'Konya',
  'f11f3330-fda2-5a35-b476-663501a13b96': 'Kütahya',
  '5df86c75-3a11-5563-a2c1-bd625ec0825b': 'Malatya',
  '5d482e8c-5cef-5cf2-81f1-6b2d2eb6d562': 'Manisa',
  '27ae1aaf-0c3f-50bc-8d84-29bdf5b4cafc': 'Kahramanmaraş',
  'f78b3441-28c7-5b64-9e28-00cb2e2c6c74': 'Mardin',
  '82a6edde-a2ab-5cdb-ae35-5c6c08bee9f4': 'Muğla',
  'bf6e9697-9e72-5d42-b391-a4f177e009a1': 'Muş',
  '7ea80ade-8e79-5287-aa57-b9679b7d2493': 'Nevşehir',
  'c0146c7d-49e6-5eac-ac4e-e6160d099932': 'Niğde',
  'd6b95015-232f-577a-ac05-dc7fd749df79': 'Ordu',
  '31ddec39-08bc-58cf-aac4-a2a5e92a1b75': 'Rize',
  '4ac1103e-e6b8-567b-871e-654699e186c9': 'Sakarya',
  'f23e4ccb-0c68-55c4-a2e0-b93e5628ed30': 'Samsun',
  'e619c5e3-0f52-553a-a5ec-7452f7577871': 'Siirt',
  'ce12c51f-b585-57b1-89f7-a2c26cee920c': 'Sinop',
  '49a980c1-397d-59a7-aa16-c3af6342fc9a': 'Sivas',
  '4885e918-b9eb-5db3-85c2-b8ffa5930b6e': 'Tekirdağ',
  '889abfb3-d544-5628-88ce-8631afaf33e0': 'Tokat',
  'f5e4bc23-3a08-549c-a90f-156c7729e5a6': 'Trabzon',
  'b2bc9402-45c7-53d2-bb5e-da697a76b856': 'Tunceli',
  'ea38567b-7f7f-55bc-a95a-e936c280de19': 'Şanlıurfa',
  '6fc5e62c-1138-57f2-9b03-12f25ab5f1b2': 'Uşak',
  '442c3df1-7610-5540-8a02-59bbb9361359': 'Van',
  'c44beff4-a64a-5c39-9e5d-930d3cfb69b8': 'Yozgat',
  'a7726d7c-e3ab-5272-9c49-4a2fd0ba77bf': 'Zonguldak',
  '8fa4aea9-359d-5066-b935-2f92126144a3': 'Aksaray',
  '3060b17f-2a00-5096-a008-4bd2d17383e7': 'Bayburt',
  '18f1efc7-d5cd-56a3-8e65-ca6de93420fb': 'Karaman',
  '9e2ecc23-1f18-52a5-8af4-653e740f225e': 'Kırıkkale',
  '66f78454-b7d4-596f-abb7-e9aaa7ba8a5a': 'Batman',
  'c40efeab-8ed2-5e0a-8352-0c0fa25178d3': 'Şırnak',
  '9755f927-625a-5986-a3aa-acd4ef20b126': 'Bartın',
  'dc431c2a-03d9-589b-8dc9-a9ccfe1162e1': 'Ardahan',
  'a98d0f3b-748f-5704-a0e9-7489cd654579': 'Iğdır',
  '1fc7e574-b545-5fef-a142-3a974584bb62': 'Yalova',
  '79a22106-cc22-559a-8d33-59c2534bc3a7': 'Karabük',
  '0a076515-a6fa-5d74-9ea4-636eac7622d7': 'Kilis',
  '696d6fc8-e340-5c77-ab2f-675496726aad': 'Osmaniye',
  '921ebfc0-8b4c-5204-a3bc-bc5d8ba86e8f': 'Düzce',
};

// In-memory cache for dynamic district lookups
const districtNameCache = new Map<string, { name: string; provinceName?: string }>();
const listeners = new Set<() => void>();

function notifyListeners() {
  listeners.forEach((fn) => {
    try {
      fn();
    } catch {}
  });
}

export function getProvinceNameByUuid(uuid?: string | null): string {
  if (!uuid) return '';
  const clean = uuid.toLowerCase().trim();
  return PROVINCES_BY_UUID[clean] || '';
}

export function getDistrictNameByUuid(uuid?: string | null): string {
  if (!uuid) return '';
  const clean = uuid.toLowerCase().trim();
  return districtNameCache.get(clean)?.name || '';
}

/**
 * Ensures district is fetched and cached if given a district UUID
 */
export async function ensureDistrictFetched(districtId: string): Promise<void> {
  const clean = districtId.toLowerCase().trim();
  if (!clean || districtNameCache.has(clean)) return;

  try {
    // Call search with limit=1 to resolve district
    const response = await apiRequest<{ items: Array<{ id: string; name: string; provinceId: string }> }>(
      'GET',
      '/api/v1/districts/search',
      undefined,
      { params: { limit: 100 } }
    );
    if (response?.items) {
      for (const item of response.items) {
        const itemClean = item.id.toLowerCase().trim();
        const pName = PROVINCES_BY_UUID[item.provinceId?.toLowerCase()?.trim()] || '';
        districtNameCache.set(itemClean, { name: item.name, provinceName: pName });
      }
      notifyListeners();
    }
  } catch {}
}

export function useResolvedLocation(detail: any): string {
  const [, setTick] = useState(0);

  useEffect(() => {
    const listener = () => setTick((t) => t + 1);
    listeners.add(listener);

    const dId = detail?.districtId ? String(detail.districtId) : '';
    if (dId && dId.includes('-') && !districtNameCache.has(dId.toLowerCase().trim())) {
      void ensureDistrictFetched(dId);
    }

    return () => {
      listeners.delete(listener);
    };
  }, [detail?.districtId]);

  if (!detail) return 'Konum Belirtilmedi';

  // 1. Direct location name if available
  if (detail.locationName && typeof detail.locationName === 'string' && detail.locationName.trim()) {
    return detail.locationName.trim();
  }

  // 2. Direct province/district names on detail or properties
  const props = (detail.properties || {}) as Record<string, any>;
  const norm = (s: string) => (s || '').toLowerCase().replace(/[-_\s]/g, '').replace(/ı/g, 'i');

  let propCity = '';
  let propDistrict = '';

  for (const [k, v] of Object.entries(props)) {
    if (!v) continue;
    const nk = norm(k);
    if (['sehir', 'il', 'city', 'province', 'iladi', 'sehiradi'].includes(nk)) {
      propCity = String(v).trim();
    }
    if (['ilce', 'district', 'town', 'ilceadi'].includes(nk)) {
      propDistrict = String(v).trim();
    }
  }

  const prov = detail.provinceName || propCity;
  const dist = detail.districtName || propDistrict;

  if (prov && dist) {
    if (prov.toLowerCase() === dist.toLowerCase()) return prov;
    return `${prov} / ${dist}`;
  }
  if (prov) return prov;
  if (dist) return dist;

  // 3. Fallback to UUID lookups
  const dId = detail.districtId ? String(detail.districtId).toLowerCase().trim() : '';
  const pId = detail.provinceId ? String(detail.provinceId).toLowerCase().trim() : '';

  const lookedUpProv = pId ? getProvinceNameByUuid(pId) : '';
  const cachedDist = dId ? districtNameCache.get(dId) : null;
  const lookedUpDist = cachedDist?.name || '';
  const finalProv = lookedUpProv || cachedDist?.provinceName || '';

  if (finalProv && lookedUpDist) {
    if (finalProv.toLowerCase() === lookedUpDist.toLowerCase()) return finalProv;
    return `${finalProv} / ${lookedUpDist}`;
  }
  if (finalProv) return finalProv;
  if (lookedUpDist) return lookedUpDist;

  if (dId && !dId.includes('-')) {
    return `Bölge: ${dId}`;
  }

  return 'Konum Belirtilmedi';
}
