export enum ArticleTypeEnum {
    JOB_ADVERTISEMENT='JOB_ADVERTISEMENT', 
    GENERAL='GENERAL',
    HORSE_SERVICE='HORSE_SERVICE', 
    RACING='RACING', 
    CORPORATE_ADVERT='CORPORATE_ADVERT', 
    STALLION_INTRODUCE='STALLION_INTRODUCE'
  }