export enum EntityStatusEnum {
  DEFAULT = "DEFAULT",
  ACTIVE = "ACTIVE",
  PASSIVE = "PASSIVE",
  DELETED = "DELETED",
  NOT_COMPLETED = "NOT_COMPLETED",
  SOLD = "SOLD",
  WAITING_APPROVAL = "WAITING_APPROVAL",
  REJECTED = "REJECTED"
}